### PR TITLE
Update / add new Bookmark icons

### PR DESCRIPTION
**Pull request by shiyaoli-1**
# New Bookmark and BookmarkFull icon

I'm adding two new icons to Stacks-Icons named Bookmark and BookmarkAlt. Bookmark replaces the old Bookmark icon. I've checked all of the following items necessary for merging this PR:

- Styles
  - [x] all icons match the existing style conventions
  - [x] all icons are aligned _exactly_ to the pixel grid to prevent blurriness
  - [x] all icons are in monochrome black/gray _or_ in their native colors
  - [x] all sizes for this icon have a matching color scheme
- Regular sized icon **required**
  - [x] my file is named `Save.svg` and `SaveFull.svg`
  - [x] the icon has a height and width of 18x18 pixels

### CODE REVIEW

**Comment by shiyaoli-1** [comment]
@dancormier Sorry Dan, I tried to add ```Stacks``` as the reviewer, but in my dropdown of reviewers I don't have ```Stacks``` as an option? Not sure why. I just added you for now please change it to someone else if needed. Thank you!

**Review by dancormier — DISMISSED** [review]
These icons look good, but I'd like to push back on the naming.

These icons read as `Bookmark` to me and I was wondering if we should use that name here. If we were to use `Bookmark`, we'd run into a [naming collision](https://stackoverflow.design/product/resources/icons/#bookmark) but I think we could work around it by changing the existing `Bookmark` icon to `BookmarkAlt`.

---


Two notes for posterity that require no action:

1) The icons have a small amount of aliasing on the left and right edges

This seems like a necessary compromise. The icon looks good and I don't believe this can be resolved without making them look wider/thinner.

2) We don't have a naming convention for `{icon}Full`

I searched through our existing icons to find one that is default unfilled and has an alt version that is filled. We have surprisingly few binary state icons (`Archive`/`ArchiveAlt`, `Eye`/`EyeOff`, `Lock`/`Unlock`, `ScreenFull`/`ScreenNormal`) and no generalized naming convention for them, so I think `{icon}`/`{icon}Full` works fine in this case.

**Comment by shiyaoli-1** [comment]
@dancormier Your comments make sense, but the old Bookmark icon is in production right now, used on every question page. If we change the name, how do we control the timing of updating the icon name on question pages? Let me know if there's a routine for that. If not, would it be okay to name the new icon BookmarkAlt instead?

**Comment by dancormier** [comment]
> If we change the name, how do we control the timing of updating the icon name on question pages? 

After we cut a new release of this package, we'd update the dependency in Core and change the name of the existing bookmark icon to reference the new name. I believe find + replace all `@SVG.Boomkark` would cover it.

> If not, would it be okay to name the new icon BookmarkAlt instead?

This approach makes sense conceptually, but the look of the existing bookmark icon really seems like it should be the `Alt` in my opinion.

image

**Comment by shiyaoli-1** [comment]
> > If we change the name, how do we control the timing of updating the icon name on question pages?
> 
> After we cut a new release of this package, we'd update the dependency in Core and change the name of the existing bookmark icon to reference the new name. I believe find + replace all `@SVG.Boomkark` would cover it.
> 




> > If we change the name, how do we control the timing of updating the icon name on question pages?
> 
> After we cut a new release of this package, we'd update the dependency in Core and change the name of the existing bookmark icon to reference the new name. I believe find + replace all `@SVG.Boomkark` would cover it.
> 
> > If not, would it be okay to name the new icon BookmarkAlt instead?
> 
> This approach makes sense conceptually, but the look of the existing bookmark icon really seems like it should be the `Alt` in my opinion.
> 
> image

Thanks Dan! If I understood this correctly, when you update the dependency you'll update the icon name in the codebase, there's no action required from us?

**Comment by dancormier** [comment]
> Thanks Dan! If I understood this correctly, when you update the dependency you'll update the icon name in the codebase, there's no action required from us?

Yep, most likely someone from the Stacks team will update the dependency and fix whatever breaking changes are introduced.

**Comment by shiyaoli-1** [comment]
> Yep, most likely someone from the Stacks team will update the dependency and fix whatever breaking changes are introduced.

Thank you so much for your help! I just updated the PR.

**Review by b-kelly — CHANGES_REQUESTED** [review]
I'm going to temporarily halt merge here (sorry!). It is not immediately clear to me whether we actually want to keep the old bookmark logo or not. Additionally, the old logo (henceforth, BookmarkAlt) does not have the same shape as the new logo. Let me put this in front of the design guild and I'll follow up with any changes that need to be made here.

**Comment by shiyaoli-1** [comment]
> I'm going to temporarily halt merge here (sorry!). It is not immediately clear to me whether we actually want to keep the old bookmark logo or not. Additionally, the old logo (henceforth, BookmarkAlt) does not have the same shape as the new logo. Let me put this in front of the design guild and I'll follow up with any changes that need to be made here.

@b-kelly No worries. To give you some background on this change, we are rolling out a new bookmarking system in public platform, and renaming it to "Saves", but not touching it in Teams and Enterprise yet. So it'd be best to keep the old the bookmark icon so Teams can continue using it.

**Review by b-kelly — CHANGES_REQUESTED** [review]
Discussed internally - we're ok with updating the bookmark icon globally. Let's follow the precedence set by `Icon/Archive` and make the filled icon `Bookmark` and the _unfilled_ icon `BookmarkAlt`. Delete the old bookmark icon completely.

This way, the old bookmark icon (filled w/ star) gets swapped out for the new filled bookmark icon everywhere.

**Comment by shiyaoli-1** [comment]
> Discussed internally - we're ok with updating the bookmark icon globally. Let's follow the precedence set by `Icon/Archive` and make the filled icon `Bookmark` and the _unfilled_ icon `BookmarkAlt`. Delete the old bookmark icon completely.

Thanks for following through this! I just updated the PR.

**Review by b-kelly — APPROVED** [review]
LGTM! Thank you for working with us in getting these in place. Doing a (visually) breaking change once is a lot easier than doing a breaking change, then updating a bunch of places, then doing another breaking change again later.

**Pull request merged**
