### PR TITLE
MailOpen Icons

### PR DESCRIPTION
**Pull request by ellenchanhy**
# New MailOpen icon, and new MailOpenSm icon

I'm adding two new icons to Stacks-Icons named MailOpen and MailOpenSm. I've checked all of the following items necessary for merging this PR:

- Styles
  - [x] all icons match the existing style conventions
  - [x] all icons are aligned _exactly_ to the pixel grid to prevent blurriness
  - [x] all icons are in monochrome black/gray _or_ in their native colors
  - [x] all sizes for this icon have a matching color scheme
- Regular sized icon **required**
  - [x] my file is named `\[ICON_NAME\].svg`
  - [x] the icon has a height and width of 18x18 pixels
- Small icon
  - [x] my file is named `\[ICON_NAME\]Sm.svg`
  - [x] the icon has a height and width of 14x14 pixels

### CODE REVIEW

**Review by marradoss — APPROVED** [review]

**Review by b-kelly — CHANGES_REQUESTED** [review]
Quick feedback until I do an actual review (using as onboarding for new design systems designer):

Should this be `ReadMail` instead of `Unread`? The opened envelope to me signifies that the message has been read (and we already have `Mail`, which is closed).

I think I'd actually rename this to `MailOpen` or `MailRead`, which is more inline with our icon naming convention.

**Comment by ellenchanhy** [comment]
@b-kelly Yes, I'm sorry, it should be `MailOpen` or `MailRead.` Thank you for catching that!

**Comment by ellenchanhy** [comment]
Icon names updated, as well as the name of the PR just so that it's less confusing.

**Review by b-kelly — APPROVED** [review]
lgtm! Thank you for the new icons. We'll cut a new release by end of week so these will be available to devs.

Looked over with SFoster as part of his onboarding

**Pull request merged**
