### PR TITLE
Created new Conversation Spot Illustration

### PR DESCRIPTION
**Pull request by ellenchanhy**
# New Conversation spot illustration

I'm adding a new spot illustration to Stacks-Icons named Conversation. I've checked all of the following items necessary for merging this PR:

- Styles
  - [ ] all spots match the existing style conventions
  - [ ] all spots are in monochrome black/gray
- Regular sized spot **required**
  - [x] my file is named `Conversation.svg`
  - [x] the spot has a height and width of 48x48 pixels
- Large spot
  - [ ] my file is named `ConversationLg.svg`
  - [ ] the spot has a height and width of 96x96 pixels
- Extra large spot
  - [ ] my file is named `ConversationXL.svg`
  - [ ] the spot has a height and width of 196x196 pixels
  - [ ] a Lg version of this spot also exists

### CODE REVIEW

**Comment by dancormier** [comment]
I think this PR will require a few tweaks:

- ~~Include `ConversationLG`, `ConversationXL` variations~~
- [ ] Replace forced color with monochrome
- [ ] Modify build files to build conversation illustrations

That should cover it, correct @b-kelly?

**Comment by b-kelly** [comment]
I'll double check this when I'm back in the office. I don't think `Lg/Xl` sizes are strictly required. We don't require them for all Icons, so I don't think we should require them for Spots either. Additionally, resubmitting as monochrome _shouldn't_ be needed, as that is taken care of in CSS iirc.

**Comment by ellenchanhy** [comment]
Thanks and please let me know if I do need to do anything on my end

**Comment by aaronshekey** [comment]
👋 This style looks outdated. You're going to want to make sure you're punching this out in the Stacks style. See the Figma doc: https://www.figma.com/file/NxAqQAi9i5XsrZSm1WYj6tsM/Icons-and-Spot-Illustrations

**Comment by b-kelly** [comment]
Looking at this today. Will get back to you with any necessary changes. 

@aaronshekey Thanks for the feedback! I'll reach out to the designers to make sure we're all on the same page in regards to style.

**Review by b-kelly — CHANGES_REQUESTED** [review]
@ellenchanhy Looks like I was wrong about the native colors. All spots need to be monochrome as we currently only support native coloring on icons. I've added some PR templates to this project with checklists of things to check for. I edited your PR description to add the checklist.

In regards to the styling of the spot itself, I'd recommend taking a look at the [PeopleXL](https://stackoverflow.design/product/resources/spots/#peoplexl) and [StarBubble](https://stackoverflow.design/product/resources/spots/#starbubble) for examples of other spots that have message bubbles in them.

**Comment by b-kelly** [comment]
@ellenchanhy Closing this PR due to inactivity. Please reopen if you would like to pursue this further.

**Pull request closed without merging**
