### PR TITLE
Update dotnet framework

### PR DESCRIPTION
**Pull request by b-kelly**
This PR updates the dotnet target framework from `netstandard2.0` to `net8.0` (the latest LTS). Despite there being no breaking changes in the code itself, I _think_ that updating the framework target is a breaking-ish change, so I also bumped the version from `6.0.2` to `7.0.0`.

The reasons for updating the framework are as follows:
1. We needed to drop the `Microsoft.AspNetCore.Html.Abstractions` standalone package
   - the standalone packages are deprecated and are now shipped in the framework reference ([further reading](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-8.0&tabs=visual-studio#use-the-aspnet-core-shared-framework)) 
2. There are no longer any new versions of `netstandard` being shipped since there is now one unified framework ([further reading](https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/))

### CODE REVIEW

**Review by giamir — COMMENTED** [review]
This looks good to me @b-kelly. 

I opened a very similar PR [here](https://github.com/StackExchange/Stacks-Icons/pull/311/files) on Friday that I then ended up closing since the pipeline issue turned out to be a different reason.

I think we might want to target 2 frameworks since in Core we are not yet on dotnet 8. 
In Stacks.Razor we are doing the same (support both 6 and 8 - Samo helped with that a while back and I did the same for the PR I ended up closing).

Thank you

**Comment by b-kelly** [comment]
@giamir Good callout. I'll review the PR you had closed to ensure that we're properly supporting net6.0 as well (for now, it's EOL soon and I know folks are working on the migration as we speak).

**Comment by giamir** [comment]
> @giamir Good callout. I'll review the PR you had closed to ensure that we're properly supporting net6.0 as well (for now, it's EOL soon and I know folks are working on the migration as we speak).

If we can target both frameworks without big headaches I would just do it to avoid having to coordinate. We can drop support for 6 later on. 🙂

**Comment by b-kelly** [comment]
@giamir Updating to target both was trivial. Ready for review!

**Review by giamir — APPROVED** [review]

**Pull request merged**
