### PR TITLE
Remove trademarked icons

### PR DESCRIPTION
**Pull request by b-kelly**
Removes all trademarked icons/logos/wordmarks since we don't allow these to be used without permission. See [our legal guidelines](https://stackoverflow.com/legal/trademark-guidance) around trademark usage.

### CODE REVIEW

**Comment by giamir** [comment]
@b-kelly This PR looks good to me but I would wait to merge it until we have decided a clear migration strategy for internal products that relies on these trademarked icons (create private packages/repos or hardcoding, documentation, etc...).

I also think we should add an MIT `LICENSE.md` file as part of this PR to highlight the fact the remaining icons are OS'ed.

**Comment by b-kelly** [comment]
@giamir I'm going to add the LICENSE file in a follow-up commit so it appears as its own line item in the changelog (well, if we were autogenerating it would...).

**Comment by b-kelly** [comment]
Merging now, since we have a clear migration strategy for all repos that rely on Stacks-Icons.

**Comment by LordKa0S** [comment]
I need to use the StackOverflow glyph in accordance with the following provisions from the trademark guidelines:

> **Do** feel free to use your profile "Flair" to reference or link to your user account. Use of unaltered logos in the context of displaying the entire content of User Flair is generally okay.
**Do** use the most current logo where applicable and permitted.

Further, from the [brand guidelines for the logo](https://stackoverflow.design/brand/logo/):

> Our logo is broken down into two components, the glyph and its wordmark.
...
These are accessible in various pixel-locked sizes within our [icons set](https://stackoverflow.design/product/resources/icons) and are available as @Svg.LogoGlyph and @Svg.LogoWordmark.

WIth this removal, there are no authoritative sources for the logo icons.

**Pull request merged**
