### PR TITLE
Do not remove xmlns from the <svg> tag - it's required.

### LINKED ISSUE #13: SVG Files are missing XMLNS, thus failing to load
The `<svg>` tag in most icons (e.g., [LogoEnterprise.svg](https://raw.githubusercontent.com/StackExchange/Stacks-Icons/master/build/lib/LogoEnterprise.svg)) is missing the `xmlns="http://www.w3.org/2000/svg"` attribute. This causes them not to load as images in Chrome, Firefox or Internet Explorer. GitHub also shows an invalid file error:  https://github.com/StackExchange/Stacks-Icons/blob/master/build/lib/LogoEnterprise.svg

~~This is already the case in the `build/lib` folder, so it's not a problem of the Gruntfile/Build process.~~

**Correction:** This **IS** a problem with the build process, the original icons are in src/export and are good: https://github.com/StackExchange/Stacks-Icons/blob/master/src/export/LogoEnterprise.svg

### PR DESCRIPTION
**Pull request by mstum**
Fixes #13

### CODE REVIEW

**Comment by aaronshekey** [comment]
This is by design, since we don't actually want folks including these icons via ``. These are meant to be directly injected via the helper as markup so they can be colored on the fly and manipulated as text.

Can you speak a bit more to the context here and why you'd introduce extra file size instead of calling `@Svg.LogoEnterprise`?

**Comment by mstum** [comment]
An example is in `Header.cshtml`, see `Custom Enterprise logo (.branded-site-logo)`. But from the look of it, other .svg files aren't used from Stacks Icons, so I think we'll have to make sure the default logo.svg (for when no custom theme is set on Enterprise) exists outside of Stacks and has the xmlns.

**Comment by aaronshekey** [comment]
I'm sure I'm missing something, but I think our header could just rely on the helper for the Enterprise logo:

```
@if (Current.Settings.Paths.LogoUrlSvg.HasValue())
{
    <img class="h-auto wmx100" src="@Current.Settings.Paths.LogoUrlSvg" alt="@site.NameWithoutStackExchange">
}
else
{
    @Svg.LogoEnterprise.With("native")
}
```

**Comment by mstum** [comment]
PR can be closed. You're right, the failing usages can be worked around with the SVG Helper.

**Pull request closed without merging**
